set(_CATKIN_CURRENT_PACKAGE "dk_camera")
set(dk_camera_VERSION "0.0.0")
set(dk_camera_MAINTAINER "slam <slam@todo.todo>")
set(dk_camera_PACKAGE_FORMAT "2")
set(dk_camera_BUILD_DEPENDS "roscpp" "std_msgs" "message_generation")
set(dk_camera_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs")
set(dk_camera_BUILDTOOL_DEPENDS "catkin")
set(dk_camera_BUILDTOOL_EXPORT_DEPENDS )
set(dk_camera_EXEC_DEPENDS "roscpp" "std_msgs" "message_runtime")
set(dk_camera_RUN_DEPENDS "roscpp" "std_msgs" "message_runtime")
set(dk_camera_TEST_DEPENDS )
set(dk_camera_DOC_DEPENDS )
set(dk_camera_URL_WEBSITE "")
set(dk_camera_URL_BUGTRACKER "")
set(dk_camera_URL_REPOSITORY "")
set(dk_camera_DEPRECATED "")